services:
  - type: web
    plan: free
    name: LazyPrincess - v-10
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/LazyDeveloperr/LazyPrincess.git      
    branch: Master
    envVars:
      - key: BOT_TOKEN 
        sync: 6781092916:AAGTdQXwOu0VgFNjB8N7EPSGvBh9zPdFvpc
      - key: API_ID 
        sync: 28773160
      - key: API_HASH
        sync: 37bdcd1fce6d5edc6f5f8b28b44c9e8c
      - key: LOG_CHANNEL
        sync: -1002024552188    
    
    autoDeploy: false
